# Generated by Django 2.0.6 on 2018-06-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', redactor.fields.RedactorField(verbose_name='Текст')),
                ('date_add', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('important', models.BooleanField(default=False, verbose_name='Важная новость')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
                'ordering': ['-date_add'],
            },
        ),
    ]
