# Generated by Django 2.0.6 on 2018-06-10 18:26

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка на страницу')),
                ('content', redactor.fields.RedactorField(verbose_name='Содержимое страницы')),
                ('group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Группа')),
            ],
            options={
                'verbose_name_plural': 'Статические страницы',
                'verbose_name': 'Статическая страница',
            },
        ),
    ]
