# Generated by Django 2.0.6 on 2018-06-10 21:00

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название раздела')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('number', models.IntegerField(default=0, help_text='Порядок отображения в меню', verbose_name='Номер раздела')),
            ],
            options={
                'ordering': ('number',),
                'verbose_name': 'Раздел сведений об ОР',
                'verbose_name_plural': 'Разделы сведений об ОР',
            },
        ),
        migrations.CreateModel(
            name='Svedenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', redactor.fields.RedactorField(verbose_name='Текст')),
                ('number', models.IntegerField(default=0, help_text='Порядок отображения внутри раздела', verbose_name='Номер')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svedenia.Group', verbose_name='Раздел')),
            ],
            options={
                'ordering': ('number',),
                'verbose_name': 'Информация об ОР',
                'verbose_name_plural': 'Информация об ОР',
            },
        ),
    ]
